# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  # def teardown_method(self, method):
  #   self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(880, 623)
    self.driver.find_element(By.NAME, "q").send_keys("test ivan")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Images").click()
    self.driver.find_element(By.CSS_SELECTOR, ".PKhmud:nth-child(4) .hIOe2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".isv-r:nth-child(2) .rg_i").click()
    self.driver.execute_script("window.scrollTo(0,133)")
    # self.driver.close()
  
