# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcaptcha():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcaptcha(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(880, 623)
    self.driver.find_element(By.NAME, "q").send_keys("https://www.google.com/recaptcha/api2/demo")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".g:nth-child(1) .LC20lb > span").click()
  
