version: "3"
services:
  guacamole-backend:
    build: .
    ports:
      - "8082:8080"
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRES_DATABASE=guacamole_db
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password