FROM python:3.7.4

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV FLASK_APP=src:create_app()
ENV FLASK_ENV=development
ENV FLASK_RUN_PORT=6001
CMD flask run --host=0.0.0.0
